/*
 *
 * DetailPage constants
 *
 */

export const RETRIEVE_SINGLE_POKEMON = 'app/DetailPage/RETRIEVE_SINGLE_POKEMON';
export const RETRIEVE_SINGLE_POKEMON_SUCCESS = 'app/DetailPage/RETRIEVE_SINGLE_POKEMON_SUCCESS';
export const RETRIEVE_SINGLE_POKEMON_FAILURE = 'app/DetailPage/RETRIEVE_SINGLE_POKEMON_FAILURE';
